version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      fontsource:
        patterns:
          - "@fontsource*"
      electron:
        patterns:
          - "electron"
          - "electron-builder"
          - "@electron/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
