#!/usr/bin/env bun
// biome-ignore-all lint/suspicious/noConsole: release packaging CLI reports progress to the operator

import { cp, readdir, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { isAbsolute, join, resolve } from "node:path";
import cac from "cac";
import {
  buildTauriSidecarResourcePlan,
  prepareTauriSidecarResources,
} from "../desktop/prepare-tauri-sidecar.ts";

const WORKSPACE_ROOT = join(import.meta.dirname, "../..");
const DEFAULT_RELEASE_DIR = "dist/release";
const TARGET_TRIPLE = "x86_64-pc-windows-msvc";
const INSTALLER_NAME = "aop-windows-x64-setup.exe";

export interface WindowsInstallerPlan {
  appName: string;
  installerPath: string;
  releaseDir: string;
  resourcesDir: string;
  runtimeAssetsArchive: string;
  targetTriple: string;
  tauriBundleDir: string;
  version: string;
  workspaceRoot: string;
}

export type WindowsSigningConfig =
  | { mode: "unsigned" }
  | { mode: "signed"; pfxBase64: string; password: string };

interface BuildWindowsInstallerPlanOptions {
  releaseDir?: string;
  version: string;
  workspaceRoot?: string;
}

interface BuildWindowsInstallerArtifactsOptions {
  releaseDir?: string;
  signingConfig?: WindowsSigningConfig;
  version?: string;
  workspaceRoot?: string;
}

interface CliOptions {
  "release-dir"?: string;
  version?: string;
}

/** The NSIS installer (distinct from the bare CLI binary aop-windows-x64.exe). */
export const resolveWindowsInstallerArtifacts = (): string[] => [INSTALLER_NAME];

export const buildWindowsInstallerPlan = ({
  releaseDir = DEFAULT_RELEASE_DIR,
  version,
  workspaceRoot = WORKSPACE_ROOT,
}: BuildWindowsInstallerPlanOptions): WindowsInstallerPlan => {
  const root = resolve(workspaceRoot);
  const resolvedReleaseDir = isAbsolute(releaseDir) ? releaseDir : join(root, releaseDir);

  return {
    appName: "AOP",
    installerPath: join(resolvedReleaseDir, INSTALLER_NAME),
    releaseDir: resolvedReleaseDir,
    resourcesDir: join(root, "apps/desktop/src-tauri/resources"),
    runtimeAssetsArchive: join(resolvedReleaseDir, "runtime-assets.tar.gz"),
    targetTriple: TARGET_TRIPLE,
    tauriBundleDir: join(
      root,
      "apps/desktop/src-tauri/target",
      TARGET_TRIPLE,
      "release/bundle/nsis",
    ),
    version,
    workspaceRoot: root,
  };
};

export const parseWindowsSigningConfig = (
  env: Partial<Record<string, string | undefined>> = process.env,
): WindowsSigningConfig => {
  const pfxBase64 = env.AOP_WINDOWS_PFX_BASE64?.trim();
  if (!pfxBase64) {
    return { mode: "unsigned" };
  }

  const password = env.AOP_WINDOWS_PFX_PASSWORD?.trim();
  if (!password) {
    throw new Error("AOP_WINDOWS_PFX_BASE64 requires AOP_WINDOWS_PFX_PASSWORD");
  }

  return { mode: "signed", pfxBase64, password };
};

/** signtool arguments to sign a file with a PFX certificate (SHA-256, RFC-3161 timestamp). */
export const buildSigntoolCommand = (path: string, pfxFile: string, password: string): string[] => [
  "signtool",
  "sign",
  "/fd",
  "sha256",
  "/f",
  pfxFile,
  "/p",
  password,
  "/tr",
  "http://timestamp.digicert.com",
  "/td",
  "sha256",
  path,
];

export const buildWindowsInstallerArtifacts = async ({
  releaseDir = DEFAULT_RELEASE_DIR,
  signingConfig = parseWindowsSigningConfig(),
  version,
  workspaceRoot = WORKSPACE_ROOT,
}: BuildWindowsInstallerArtifactsOptions = {}): Promise<string[]> => {
  ensureWindowsHost();

  const buildVersion = version ?? (await readPackageVersion(workspaceRoot));
  const plan = buildWindowsInstallerPlan({ releaseDir, version: buildVersion, workspaceRoot });

  await prepareTauriSidecarResources(
    buildTauriSidecarResourcePlan({
      arch: "x64",
      platform: "windows",
      releaseDir: plan.releaseDir,
      workspaceRoot: plan.workspaceRoot,
    }),
  );
  await runCommand(["rustup", "target", "add", plan.targetTriple], plan.workspaceRoot);
  await runCommand(
    [
      "bun",
      "run",
      "--filter",
      "@aop/desktop",
      "tauri",
      "build",
      "--ci",
      "--bundles",
      "nsis",
      "--target",
      plan.targetTriple,
    ],
    plan.workspaceRoot,
    { CI: "true" },
  );

  const generatedInstaller = await findGeneratedNsisInstaller(plan.tauriBundleDir);
  await cp(generatedInstaller, plan.installerPath);
  await signInstaller(plan.installerPath, signingConfig, plan.workspaceRoot);
  console.log(`Built ${plan.installerPath}`);

  // Note: global checksums.sha256 is generated by the central release job (WIN-19/WIN-20),
  // not here, so the Windows installer is covered alongside every other artifact.
  return [plan.installerPath];
};

const signInstaller = async (
  installerPath: string,
  signingConfig: WindowsSigningConfig,
  workspaceRoot: string,
): Promise<void> => {
  if (signingConfig.mode === "unsigned") {
    return;
  }

  const pfxFile = join(tmpdir(), "aop-windows-signing.pfx");
  await writeFile(pfxFile, Buffer.from(signingConfig.pfxBase64, "base64"));
  await runCommand(
    buildSigntoolCommand(installerPath, pfxFile, signingConfig.password),
    workspaceRoot,
  );
};

const readPackageVersion = async (workspaceRoot: string): Promise<string> => {
  const packageJson = await Bun.file(join(workspaceRoot, "package.json")).json();
  return String(packageJson.version);
};

const ensureWindowsHost = (): void => {
  if (process.platform !== "win32") {
    throw new Error("Windows installer packaging requires a Windows host with Tauri + NSIS");
  }
};

const runCommand = async (
  command: string[],
  cwd: string,
  env: Record<string, string> = {},
): Promise<void> => {
  const proc = Bun.spawn(command, {
    cwd,
    env: { ...process.env, ...env },
    stderr: "inherit",
    stdout: "inherit",
  });

  const exitCode = await proc.exited;
  if (exitCode !== 0) {
    throw new Error(`Command failed (${exitCode}): ${command.join(" ")}`);
  }
};

const findGeneratedNsisInstaller = async (bundleDir: string): Promise<string> => {
  const entries = await readdir(bundleDir);
  const candidates = await Promise.all(
    entries
      .filter((entry) => entry.endsWith(".exe"))
      .map(async (entry) => {
        const path = join(bundleDir, entry);
        return { path, modifiedMs: (await stat(path)).mtimeMs };
      }),
  );

  const latest = candidates.toSorted((a, b) => b.modifiedMs - a.modifiedMs)[0];
  if (!latest) {
    throw new Error(`Tauri did not produce an NSIS installer in ${bundleDir}`);
  }

  return latest.path;
};

const main = async (): Promise<void> => {
  const cli = cac("windows-installer");
  cli
    .option("--release-dir <path>", "Release artifact directory", { default: DEFAULT_RELEASE_DIR })
    .option("--version <version>", "Version label for the installer");

  const { options } = cli.parse();
  await buildWindowsInstallerArtifacts({
    releaseDir: (options as CliOptions)["release-dir"],
    version: (options as CliOptions).version,
  });
};

if (import.meta.main) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
